env:
  - NO_CONFIRM=true

jobs:
  include:
    - stage: prelude_test_osx
      install: true
      os: osx
      osx_image: xcode10.2
      script: ADIFY_TEST=true ./prelude.sh
    - stage: prelude_test_ubuntu
      install: true
      os: linux
      dist: trusty
      script: ADIFY_TEST=true ./prelude.sh
    - if: env(TRAVIS_COMMIT_MESSAGE) =~ [FULL_TEST_CI]
      stage: full_prelude_test_ubuntu
      install: true
      os: linux
      dist: trusty
      script: travis_wait ./prelude.sh
    - if: env(TRAVIS_COMMIT_MESSAGE) =~ [FULL_TEST_CI]
      script: full_prelude_test_osx
      install: true
      os: osx
      osx_image: xcode10.2
      script: travis_wait ./prelude.sh
